### ISSUE TITLE
[refactor] UI 수정

### ISSUE THREAD

**Issue by Hj1218** [TUK-DP/frontend#209]
### 리팩토링 할 부분
- [ ] 치매진단 시작페이지
- [ ] 진단결과 치매예방법
- [ ] 일기 작성
- [ ] 일기 열기 (일기 내용)
- [ ] 치매센터 검색페이지

**Comment by Leewonchan14** [comment]
https://github.com/TUK-DP/frontend/issues/210
으로 통일
